# Generated by Django 3.2.3 on 2021-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210523_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='file_name',
            field=models.FileField(null=True, upload_to='accounts'),
        ),
    ]
