# Generated by Django 3.2.3 on 2021-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_fournisseur_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
