# Generated by Django 3.2.3 on 2021-05-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210527_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='pieces',
        ),
    ]
