# Generated by Django 3.2.3 on 2021-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210527_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
