# Generated by Django 3.2.3 on 2021-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_fournisseur_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='reference_fabricant',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='projet',
            new_name='Project_Ref',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='reference_fournisseur',
            new_name='Requester',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='reference_piece',
            new_name='Speciality',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='fournisseur',
            new_name='Supplier',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='fabricant',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='quantite_piece',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='statut',
        ),
        migrations.AddField(
            model_name='commande',
            name='Delivery_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='Estimated_Delivery_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='Final_Cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='PO_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='PO_Number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Application_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Desired_Delivery_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Devise',
            field=models.CharField(blank=True, choices=[('Dinar', 'Dinar'), ('Dollar', 'Dollar'), ('Euro', 'Euro')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Cost_Cotation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Delivery_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Num_RFQ',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='PO_Customer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Quotation_Number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
