# Generated by Django 3.2.3 on 2021-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210531_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='demande',
            new_name='Request',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
