# Generated by Django 3.2.3 on 2021-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210531_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
