# Generated by Django 3.2.3 on 2021-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_fournisseur_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(blank=True, choices=[('Validée', 'Validée'), ('Non Validée', 'Non Validée')], max_length=200, null=True),
        ),
    ]
