# Generated by Django 3.2.3 on 2021-05-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_demande_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='statut',
            new_name='status',
        ),
    ]
