# Generated by Django 3.2.3 on 2021-05-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_rename_statut_demande_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='status',
            new_name='statut',
        ),
    ]
