# Generated by Django 3.2.3 on 2021-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_rename_status_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Desired_Delivery_Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Initial_Delivery_Date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
