# Generated by Django 3.2.3 on 2021-06-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210601_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande'),
        ),
    ]
