# Generated by Django 3.2.3 on 2021-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210601_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Desired_Delivery_Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Initial_Delivery_Date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
