# Generated by Django 3.2.3 on 2021-06-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210601_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Devise',
            field=models.CharField(choices=[('Dinar', 'Dinar'), ('Dollar', 'Dollar'), ('Euro', 'Euro')], max_length=200, null=True),
        ),
    ]
