# Generated by Django 3.2.3 on 2021-06-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210602_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_validée',
            name='demande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande'),
        ),
    ]
