# Generated by Django 3.2.3 on 2021-06-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_demande_validée_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande_validée'),
        ),
    ]
