# Generated by Django 3.2.3 on 2021-06-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210602_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('po', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='Initial_Cost_Cotation',
            new_name='Initial_Cost_Cotation_1',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='Initial_Delivery_Date',
            new_name='Initial_Delivery_Date_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Devise',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Num_RFQ',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Quotation_Number',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Supplier',
        ),
        migrations.AddField(
            model_name='demande',
            name='Devise_1',
            field=models.CharField(choices=[('TND', 'TND'), ('€', '€'), ('$', '$')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Devise_2',
            field=models.CharField(choices=[('TND', 'TND'), ('€', '€'), ('$', '$')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Devise_3',
            field=models.CharField(choices=[('TND', 'TND'), ('€', '€'), ('$', '$')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='File_1',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='demande',
            name='File_2',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='demande',
            name='File_3',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Cost_Cotation_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Cost_Cotation_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Delivery_Date_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Initial_Delivery_Date_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Quotation_Number_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Quotation_Number_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Quotation_Number_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Request_Type',
            field=models.CharField(choices=[('Demande Regulière', 'Demande Regulière'), ('Frais géneraux (SAMM)', 'Frais géneraux (SAMM)'), ('Immobilisation (SAMM)', 'Immobilisation (SAMM)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Supplier_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp1', to='accounts.fournisseur'),
        ),
        migrations.AddField(
            model_name='demande',
            name='Supplier_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp2', to='accounts.fournisseur'),
        ),
        migrations.AddField(
            model_name='demande',
            name='Supplier_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp3', to='accounts.fournisseur'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employé'),
        ),
        migrations.CreateModel(
            name='POCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='demande',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='PO_Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pocustomer'),
        ),
    ]
