# Generated by Django 3.2.3 on 2021-06-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210604_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocustomer',
            name='customer',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='Initial_Cost_Cotation_1',
            new_name='Initial_Cost_Cotation',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='Initial_Delivery_Date_1',
            new_name='Initial_Delivery_Date',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='Initial_Cost_Cotation_2',
            new_name='Quotation_Number',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Devise_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Devise_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Devise_3',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='File_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='File_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='File_3',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Cost_Cotation_3',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Delivery_Date_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Delivery_Date_3',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Quotation_Number_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Quotation_Number_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Quotation_Number_3',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Request_Type',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Supplier_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Supplier_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Supplier_3',
        ),
        migrations.AddField(
            model_name='demande',
            name='Devise',
            field=models.CharField(choices=[('TND', 'Dinar'), ('$', 'Dollar'), ('€', 'Euro')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fournisseur'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='PO_Customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Requester',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='POCustomer',
        ),
    ]
