# Generated by Django 3.2.3 on 2021-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_demande_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='PO_Customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
