# Generated by Django 3.2.3 on 2021-06-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210604_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
