# Generated by Django 3.2.3 on 2021-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_demande_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='File_1',
            field=models.FileField(blank='true', null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='demande',
            name='File_2',
            field=models.FileField(blank='true', null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='demande',
            name='File_3',
            field=models.FileField(blank='true', null=True, upload_to=None),
        ),
    ]
