# Generated by Django 3.2.3 on 2021-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20210607_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_validée',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='demande_validée',
            name='validateur',
        ),
        migrations.AddField(
            model_name='demande_validée',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
