# Generated by Django 3.2.3 on 2021-06-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20210607_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_validée',
            name='demande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande'),
        ),
    ]
