# Generated by Django 3.2.3 on 2021-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_demande_validée_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Request_Type',
            field=models.CharField(choices=[('Besoin Projet', 'Besoin Projet'), ('Frais géneraux (SAMM)', 'Frais géneraux (SAMM)'), ('Immobilisation (SAMM)', 'Immobilisation (SAMM)')], max_length=200, null=True),
        ),
    ]
