# Generated by Django 3.2.3 on 2021-06-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_demande_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Delivery_Date_1',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Delivery_Date_2',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Initial_Delivery_Date_3',
        ),
        migrations.AddField(
            model_name='demande',
            name='Delay_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Delay_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='Delay_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='Request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.demande_validée'),
        ),
        migrations.AlterField(
            model_name='demande_validée',
            name='demande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.demande'),
        ),
    ]
