# Generated by Django 3.2.3 on 2021-06-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20210610_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.demande_validée'),
        ),
        migrations.AlterField(
            model_name='demande_validée',
            name='demande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.demande'),
        ),
    ]
